# [[ADIB]]

Using provided password for truststore and keystore:
```text
ssl Passwords:
		vault_pwd: PdShe3B7nX7m7!h7
		keystore: xV3J5*pc#MP06YGQ
		truststore: 0Y%Zw0NLas57It0H`
```

### Secret Encryption
We need to use the same vault password for all secrets in order to be able to decrypt it in unattended mode.

*Command to encrypt a secret:*
```bash
 ansible-vault encrypt_script <secret>
``` 
*Output:*
```
!vault |
          $ANSIBLE_VAULT;1.1;AES256
          37303732663733633061656535633561666235363138336664333331626562313133356437663733
          6332663134646535326265623662613232396666636636330a656639396436343938383363616537
          62376566396166646463623336656136633930306363653365323730366134353332353265633663
          3162623862643762350a303832346331336637356566363334656461303835653035646336643733
          3265
```
**Note: It's important to maintain the indentation, if not it will fail**

*Run playbook asking for vault password*
```bash
ansible-playbook -i host.yml --ask-vault-password
```

### KSQL
Checking state we face this problem connecting to the server from one of KSQL nodes:
```log
[2022-02-02 15:02:35,039] ERROR Unhandled exception (io.confluent.ksql.api.server.ServerVerticle:376)
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a0000240400000000000001000010000002000000000003000000640004001000000005000040000006000020000000040800000000007fff0000
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1213)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-02-02 15:03:06,760] ERROR Unhandled exception (io.confluent.ksql.api.server.ServerVerticle:376)
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a0000240400000000000001000010000002000000000003000000640004001000000005000040000006000020000000040800000000007fff0000
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1213)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
```
We can decrypt the record: 
````bash
printf '505249202a20485454502f322e300d0a0d0a534d0d0a0d0a0000240400000000000001000010000002000000000003000000640004001000000005000040000006000020000000040800000000007fff0000' | xxd -r -p | xxd
````

```` text
00000000: 5052 4920 2a20 4854 5450 2f32 2e30 0d0a  PRI * HTTP/2.0..
00000010: 0d0a 534d 0d0a 0d0a 0000 2404 0000 0000  ..SM......$.....
00000020: 0000 0100 0010 0000 0200 0000 0000 0300  ................
00000030: 0000 6400 0400 1000 0000 0500 0040 0000  ..d..........@..
00000040: 0600 0020 0000 0004 0800 0000 0000 7fff  ... ............
00000050: 0000
````

Seems to be a dns solve issue: we are trying to connect to the other node, connecting to the same node the problem is solved.
*Command to connect to the server solving the log issue*
````bash
KSQL_OPTS="-Djava.io.tmpdir=/some/writable/directory -Dlog4j.configuration=file:/path/to/log4j-file.properties" ksql --config-file ssl-config.properties  https://localhost:8088 -Dlog4j.configuration=file:/Users/mikebin/cp/confluent-7.0.1/etc/ksqldb/log4j.properties
````

### Connect

After changing connect user can't reboot due folder permission are granted to the old user so we reset machine manually deleting the folders

```bash
Wednesday 02 February 2022 19:51:07 +0400 (0:00:00.169) 0:01:28.640 ****
fatal: [lpp2azapkfb1.adib.co.ae]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/confluent secret file encrypt --config-file /opt/confluent/etc/kafka/server.properties --local-secrets-file /var/ssl/private/kafka-broker-security.properties --remote-secrets-file /var/ssl/private/kafka-broker-security.properties\n", "delta": "0:00:00.041102", "end": "2022-02-02 19:51:08.127196", "msg": "non-zero return code", "rc": 1, "start": "2022-02-02 19:51:08.086094", "stderr": "Error: you must log in to Confluent Platform to use this command\n\nSuggestions:\n Log in with \"confluent login --url <mds-url>\".", "stderr_lines": ["Error: you must log in to Confluent Platform to use this command", "", "Suggestions:", " Log in with \"confluent login --url <mds-url>\"."], "stdout": "", "stdout_lines": []}
fatal: [lpp1apkfb2.adib.co.ae]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/confluent secret file encrypt --config-file /opt/confluent/etc/kafka/server.properties --local-secrets-file /var/ssl/private/kafka-broker-security.properties --remote-secrets-file /var/ssl/private/kafka-broker-security.properties\n", "delta": "0:00:00.049201", "end": "2022-02-02 19:51:08.151917", "msg": "non-zero return code", "rc": 1, "start": "2022-02-02 19:51:08.102716", "stderr": "Error: you must log in to Confluent Platform to use this command\n\nSuggestions:\n Log in with \"confluent login --url <mds-url>\".", "stderr_lines": ["Error: you must log in to Confluent Platform to use this command", "", "Suggestions:", " Log in with \"confluent login --url <mds-url>\"."], "stdout": "", "stdout_lines": []}
fatal: [lpp2azapkfb2.adib.co.ae]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/confluent secret file encrypt --config-file /opt/confluent/etc/kafka/server.properties --local-secrets-file /var/ssl/private/kafka-broker-security.properties --remote-secrets-file /var/ssl/private/kafka-broker-security.properties\n", "delta": "0:00:00.040704", "end": "2022-02-02 19:51:08.170609", "msg": "non-zero return code", "rc": 1, "start": "2022-02-02 19:51:08.129905", "stderr": "Error: you must log in to Confluent Platform to use this command\n\nSuggestions:\n Log in with \"confluent login --url <mds-url>\".", "stderr_lines": ["Error: you must log in to Confluent Platform to use this command", "", "Suggestions:", " Log in with \"confluent login --url <mds-url>\"."], "stdout": "", "stdout_lines": []}
```

### Control Center

- Control center can't configure the Connect cluster,  Control center has not connectivity with one of the workers that unfortunately was the leader. **ADIB need to check this errors**
- **As workaround** we stop the no connected worker, the other become leader and we C3 can register the connect cluster